main:
  - name: About
    url: https://hyruo.com/article/fastest-personal-navigation-website/
    params:
      icon:
        vendor: simple
        name: readme

apps:
  - name: Hyruo Blog
    url: https://hyruo.com
    weight: 1
    params:
      icon:
        vendor: simple
        name: hugo

  - name: Hyruo News
    url: https://news.hyruo.com
    weight: 1
    params:
      icon:
        vendor: simple
        name: feedly

  - name: Hyruo Status
    url: https://status.hyruo.com
    weight: 2
    params:
      icon:
        vendor: simple
        name: linux

  - name: Hyruo Tests
    url: https://fosu.cc
    weight: 12
    params:
      icon:
        vendor: simple
        name: hexo

  - name: Hyruo Editor
    url: https://editor.hyruo.com
    weight: 4
    params:
      icon:
        vendor: simple
        name: markdown

  - name: Hyruo Photo
    url: https://photo.hyruo.com
    weight: 7
    params:
      icon:
        vendor: simple
        name: instagram

  - name: Hyruo Video
    url: https://video.hyruo.com
    weight: 7
    params:
      icon:
        vendor: simple
        name: youtube

  - name: Hyruo Analysis
    url: https://analysis.hyruo.com
    weight: 3
    params:
      icon:
        vendor: simple
        name: googleanalytics

  - name: Hyruo Mirror2
    url: https://backup.hyruo.com
    weight: 10
    params:
      icon:
        vendor: simple
        name: oracle

  - name: Hyruo Mirror
    url: https://blog.hyruo.com
    weight: 9
    params:
      icon:
        vendor: simple
        name: cloudflare

  - name: Hyruo Chat
    url: https://chat.hyruo.com
    weight: 4
    params:
      icon:
        vendor: simple
        name: openai

  - name: Hyruo File
    url: https://cloud.hyruo.com
    weight: 5
    params:
      icon:
        vendor: simple
        name: box

  - name: Hyruo Download
    url: https://yun.hyruo.com
    weight: 6
    params:
      icon:
        vendor: simple
        name: dropbox

  - name: Hyruo Coding
    url: https://note.leftn.com
    weight: 4
    params:
      icon:
        vendor: simple
        name: git

  - name: Hyruo Browser
    url: https://web.fosu.cc
    weight: 3
    params:
      icon:
        vendor: simple
        name: firefox

  - name: Hyruo Reader
    url: https://reader.hyruo.com
    weight: 7
    params:
      icon:
        vendor: simple
        name: wikipedia

  - name: Hyruo Ai
    url: https://ai.hyruo.com
    weight: 7
    params:
      icon:
        vendor: simple
        name: ollama

  - name: Hyruo Feeds
    url: https://feeds.hyruo.com
    weight: 8
    params:
      icon:
        vendor: simple
        name: buzzfeed