main:
  - name: About
    url: https://lawtee.com/article/fastest-personal-navigation-website/
    params:
      icon:
        vendor: simple
        name: readme

apps:
  - name: 老T博客
    url: https://Lawtee.com
    weight: 1
    params:
      icon:
        vendor: simple
        name: hugo

  - name: 个人动态
    url: https://news.hyruo.com
    weight: 2
    params:
      icon:
        vendor: simple
        name: feedly

  - name: 服务器探针
    url: https://status.hyruo.com
    weight: 3
    params:
      icon:
        vendor: simple
        name: linux

  - name: Lawtee Tests
    url: https://fosu.cc
    weight: 12
    params:
      icon:
        vendor: simple
        name: hexo

  - name: MD编辑器
    url: https://editor.hyruo.com
    weight: 4
    params:
      icon:
        vendor: simple
        name: markdown

  - name: 图库
    url: https://photo.hyruo.com
    weight: 7
    params:
      icon:
        vendor: simple
        name: instagram

  - name: 火狐
    url: https://video.hyruo.com
    weight: 7
    params:
      icon:
        vendor: simple
        name: youtube

  - name: 网站统计
    url: https://stats.lawtee.com
    weight: 3
    params:
      icon:
        vendor: simple
        name: googleanalytics

  - name: NAS
    url: https://epson.hyruo.com
    weight: 10
    params:
      icon:
        vendor: simple
        name: oracle

  - name: 海若
    url: https://hyruo.com
    weight: 9
    params:
      icon:
        vendor: simple
        name: cloudflare

  - name: 资源搜索
    url: https://search.hyruo.com
    weight: 4
    params:
      icon:
        vendor: simple
        name: openai

  - name: 文件共享
    url: https://cloud.hyruo.com
    weight: 5
    params:
      icon:
        vendor: simple
        name: box

  - name: 云盘管理
    url: https://yun.hyruo.com
    weight: 6
    params:
      icon:
        vendor: simple
        name: dropbox

  - name: 代码编辑
    url: https://note.hyruo.com
    weight: 4
    params:
      icon:
        vendor: simple
        name: git

  - name: Chrome
    url: https://web.fosu.cc
    weight: 3
    params:
      icon:
        vendor: simple
        name: firefox

  - name: 小说阅读
    url: https://reader.hyruo.com
    weight: 7
    params:
      icon:
        vendor: simple
        name: wikipedia

  - name: RSS阅读
    url: https://rss.fosu.cc/
    weight: 7
    params:
      icon:
        vendor: simple
        name: ollama

  - name: 订阅管理
    url: https://feeds.hyruo.com
    weight: 8
    params:
      icon:
        vendor: simple
        name: buzzfeed