main:
  - name: About
    url: https://lawtee.com/article/fastest-personal-navigation-website/
    params:
      icon:
        vendor: simple
        name: readme

apps:
  - name: Lawtee Blog
    url: https://Lawtee.com
    weight: 1
    params:
      icon:
        vendor: simple
        name: hugo

  - name: Lawtee News
    url: https://news.hyruo.com
    weight: 1
    params:
      icon:
        vendor: simple
        name: feedly

  - name: Lawtee Status
    url: https://status.hyruo.com
    weight: 2
    params:
      icon:
        vendor: simple
        name: linux

  - name: Lawtee Tests
    url: https://fosu.cc
    weight: 12
    params:
      icon:
        vendor: simple
        name: hexo

  - name: Lawtee Editor
    url: https://editor.hyruo.com
    weight: 4
    params:
      icon:
        vendor: simple
        name: markdown

  - name: Lawtee Photo
    url: https://photo.hyruo.com
    weight: 7
    params:
      icon:
        vendor: simple
        name: instagram

  - name: Lawtee Video
    url: https://video.hyruo.com
    weight: 7
    params:
      icon:
        vendor: simple
        name: youtube

  - name: Lawtee Stats
    url: https://stats.lawtee.com
    weight: 3
    params:
      icon:
        vendor: simple
        name: googleanalytics

  - name: Lawtee Mirror2
    url: https://backup.hyruo.com
    weight: 10
    params:
      icon:
        vendor: simple
        name: oracle

  - name: Lawtee Mirror
    url: https://blog.lawtee.com
    weight: 9
    params:
      icon:
        vendor: simple
        name: cloudflare

  - name: Lawtee Chat
    url: https://chat.hyruo.com
    weight: 4
    params:
      icon:
        vendor: simple
        name: openai

  - name: Lawtee File
    url: https://cloud.hyruo.com
    weight: 5
    params:
      icon:
        vendor: simple
        name: box

  - name: Lawtee Download
    url: https://yun.hyruo.com
    weight: 6
    params:
      icon:
        vendor: simple
        name: dropbox

  - name: Lawtee Coding
    url: https://note.leftn.com
    weight: 4
    params:
      icon:
        vendor: simple
        name: git

  - name: Lawtee Browser
    url: https://web.fosu.cc
    weight: 3
    params:
      icon:
        vendor: simple
        name: firefox

  - name: Lawtee Reader
    url: https://reader.hyruo.com
    weight: 7
    params:
      icon:
        vendor: simple
        name: wikipedia

  - name: Lawtee Ai
    url: https://ai.hyruo.com
    weight: 7
    params:
      icon:
        vendor: simple
        name: ollama

  - name: Lawtee Feeds
    url: https://feeds.hyruo.com
    weight: 8
    params:
      icon:
        vendor: simple
        name: buzzfeed