name: Translate Markdown Files

on:
  push:
    branches:
      - master  # 在 master 分支推送时触发
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行

jobs:
  translate:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # 保留 Git 凭据

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 指定 Python 版本

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      # 4. 运行翻译脚本
      - name: Run translation script
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}  # 从 GitHub Secrets 获取 API 密钥
        run: |
          python translate.py

      # 5. 提交更改
      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          script: |
            const { execSync } = require('child_process');
            execSync('git config --global user.name "h2dcc"');
            execSync('git config --global user.email "hechujie@live.com"');
            execSync('git add .');
            execSync('git diff --quiet && git diff --staged --quiet || git commit -m "Auto-translate Markdown files"');
            execSync('git push');